-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Auditoria de arquivos streaming

-- COMMAND ----------

USE CATALOG dev;
USE SCHEMA dividas;

-- COMMAND ----------

select * from dev.dividas.audit_ingestao

